version: '3'
services:

  wordpress:
    container_name: "Wordpress"
    #image: php:7.2-apache
    build:
      context: ./files/wordpress
      dockerfile: dockerfile
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./volumes/wordpress:/var/www/html/

  mariadb:
    container_name: "MariaDB"
    image: mariadb
    ports:
      - "3308:3306"
    expose:
      - "3308"
    environment:
      MYSQL_ROOT_PASSWORD: "miquelangel"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "mangel"
      MYSQL_PASSWORD: "miquelangel"

  adminer:
    container_name: "Database_Manager"
    image: adminer
    restart: always
    ports:
      - 8080:8080