FROM maven:3-openjdk-11

# Update dels paquests de Linux

# Directori principal (working directory) /app

# Copiem el programa a dins la carpeta /app

# Executem: mvn clean install -DskipTests

# Copiem la clau de Classroom per emprar els serveis de Google
