  version: '3'
  services:

    mariadb:
      image: mariadb:10.7
      ports:
        - 3308:3306
      expose:
        - 3308
      environment:
        MYSQL_ROOT_PASSWORD: "miquelangel"
        MYSQL_DATABASE: "wordpress"
        MYSQL_USER: "mangel"
        MYSQL_PASSWORD: "miquelangel"

    apache-php:
      build:
        context: ./dockerfiles
        dockerfile: apache
      ports:
        - 81:80
      expose:
        - 81
      volumes:
        - ./volumes/apache-php:/var/www/html/

    adminer:
      image: adminer:4.8.1
      restart: always
      tty: true
      stdin_open: true
      
      ports:
        - 8081:8080
      expose:
        - 8081