version: '3'
services:

  basededades:
  image: mariadb:10.7
  environment:
    - MARIADB_ROOT_PASSWORD=sistemes
    - MARIADB_DATABASE=gestibgsuite
    - MARIADB_USER=gestibgsuite
    - MARIADB_PASSWORD=gestibgsuite
  ports:
    - 3307:3306
  expose:
    - 3307
  volumes:
    - ./volumes/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.1.3-apache
    restart: always
    ports:
      - 8083:80
    expose:
      - 8083
    environment:
      - PMA_ARBITRARY=1