-- MySQL Script generated by MySQL Workbench
-- Thu May 30 13:07:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemesinformatics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemesinformatics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `si` DEFAULT CHARACTER SET utf8 ;
USE `si` ;

-- -----------------------------------------------------
-- Table `sistemesinformatics`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `si`.`user` (
                                                            `iduser` INT NOT NULL AUTO_INCREMENT,
                                                            `email` VARCHAR(255) NOT NULL,
                                                            `password` VARCHAR(255) NOT NULL,
                                                            PRIMARY KEY (`iduser`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemesinformatics`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `si`.`product` (
                                                               `idproduct` INT NOT NULL AUTO_INCREMENT,
                                                               `description` VARCHAR(45) NOT NULL,
                                                               `name` VARCHAR(45) NOT NULL,
                                                               `price` VARCHAR(45) NOT NULL,
                                                               `observations` VARCHAR(45) NOT NULL,
                                                               `user_iduser` INT NOT NULL,
                                                               PRIMARY KEY (`idproduct`, `user_iduser`),
                                                               INDEX `fk_product_user_idx` (`user_iduser` ASC),
                                                               CONSTRAINT `fk_product_user`
                                                                   FOREIGN KEY (`user_iduser`)
                                                                       REFERENCES `sistemesinformatics`.`user` (`iduser`)
                                                                       ON DELETE NO ACTION
                                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
